### ISSUE TITLE
Verification Email not being received

### ISSUE THREAD

**Issue by jereywill72** [skwerlman/skwerlman.github.io#10]
I am not receiving the verification email after registering an account. I've tried three different times with three different emails.

**Comment by skwerlman** [comment]
Hi, sorry for the inconvenience. Can you provide me with one of the account names you tried to register so i can activate it manually?

**Comment by MatthewSmith92** [comment]
Hello there! Sorry if I am not in the correct place but my friend is experiencing the same problem. He wants to register to play with us and used different emails and never got any registration email from Cockatrice .... Can anyone help?

**Comment by skwerlman** [comment]
> Hello there! Sorry if I am not in the correct place but my friend is experiencing the same problem. He wants to register to play with us and used different emails and never got any registration email from Cockatrice .... Can anyone help?

Hi, sorry for the late reply. Can you open a new issue with the username they signed up with?

**Comment by skwerlman** [comment]
@jereywill72 this has been open without updates for a while, so i'm gonna close it. if you still need help with your account, feel free to reopen it with the needed information
