### ISSUE TITLE
Verification email not received for Tetrarch registration

### ISSUE THREAD

**Issue by MatthewSmith92** [skwerlman/skwerlman.github.io#11]
Hey again! 

One of my friend is not receiving the verification email after registering on Tetrarch to play MTG with us. He tried different emails, I also tried for him with my secondary email address and also didn't get anything. 

The last username tried was Sondre1430 I believe. 

Thank you in advance for your help!

Matthew

**Comment by skwerlman** [comment]
hi, very sorry about the late reply! the account should be active now
