### ISSUE TITLE
Verification Email not being received

### ISSUE THREAD

**Issue by Sacharkin** [skwerlman/skwerlman.github.io#15]
Hi, I registered a new account on your server but do not get the activation token by mail.
Spam and Junk mails checked, too 🕵🏻

**Comment by skwerlman** [comment]
hi, sorry for the inconvenience! if you add the account name you registered with to this report, i cn activate it manually for you.

**Comment by Sacharkin** [comment]
Yes, please. It should be the same.

**Comment by skwerlman** [comment]
ok, your account should be activate now

**Comment by Sacharkin** [comment]
Thanks a lot. I am able to connect now.
