### ISSUE TITLE
[Activation]: No activation email after registration process

### ISSUE THREAD

**Issue by heavenblade** [skwerlman/skwerlman.github.io#16]
### Account Name

HeavenBlade

### Reason

Never recieved email

### Other Info

Hello! Opening this ticket since I haven't been receiving any activation email from the server after I completed the registration procedure.
Would be awesome if this could be activated manually! Thank you very much in advance!

### Server

- [X] This issue occurs on the Tetrarch Cockatrice server (mtg.tetrarch.co)

**Comment by skwerlman** [comment]
Hi, your account should be activated now.
