### ISSUE TITLE
[Activation]: Verification mail not received

### ISSUE THREAD

**Issue by tviel** [skwerlman/skwerlman.github.io#17]
### Account Name

Psychoth

### Reason

Never recieved email

### Other Info

Hi, I did not receive the activation mail for tetrarch server. Spam / Junk checked.

My registered user name is: psychoth.

Thanks.

### Server

- [X] This issue occurs on the Tetrarch Cockatrice server (mtg.tetrarch.co)

**Comment by skwerlman** [comment]
Hi, sorry for the inconvenience. your account should be active now
