### ISSUE TITLE
Not recieving an activation code

### ISSUE THREAD

**Issue by Dobbykroket** [skwerlman/skwerlman.github.io#2]
Hi!

I just registered for the server, but I did not recieve any mails with an activation code. I had the same problem for chickatrice.

does anyone know how to fix this?

**Comment by skwerlman** [comment]
This is for the tetrarch server, correct? What username did you register with?

**Comment by Dobbykroket** [comment]
yeah, it is.

I've registered under DobbyKroket

**Comment by skwerlman** [comment]
I'm updating the server atm, but as soon as it's back up i'll manually activate your acct, and look into why the email didn't reach you.

**Comment by skwerlman** [comment]
I've sent you an email with the activation token from an unblocked address, as well as some additional information.

**Comment by Dobbykroket** [comment]
Hey, sorry to bother you again, but I did not recieve the email
