### ISSUE TITLE
[Activation]: Verification mail not received

### ISSUE THREAD

**Issue by Cutugn** [skwerlman/skwerlman.github.io#20]
### Account Name

CodeSak

### Reason

Never recieved email

### Other Info

Hi, like many I haven't received the activation mail. Username is CodeSak. Thank you in advance!

### Server

- [X] This issue occurs on the Tetrarch Cockatrice server (mtg.tetrarch.co)

**Comment by skwerlman** [comment]
hi, sorry for the inconvenience! your account should be active now
