### ISSUE TITLE
Didn't get a confirmation email

### ISSUE THREAD

**Issue by efar27** [skwerlman/skwerlman.github.io#23]
I didn't get a confirmation email when I registered with the server a few days ago and can't access it. I checked my alternate categories and spam, but I'm sure I haven't gotten it.

**Comment by skwerlman** [comment]
Hi, what username did you sign up with?

**Comment by efar27** [comment]
anisis

**Comment by skwerlman** [comment]
hi, sorry for the very late response; your account should be activated now
