### ISSUE TITLE
[Activation]: 

### ISSUE THREAD

**Issue by spicytomato23** [skwerlman/skwerlman.github.io#26]
### Account Name

spicytomato

### Reason

Never recieved email

### Server

- [X] This issue occurs on the Tetrarch Cockatrice server (mtg.tetrarch.co)

**Comment by spicytomato23** [comment]
i tryed to do another registration  with a different e-mail but the issue is the same no mail recived

**Comment by skwerlman** [comment]
Hi, sorry for the trouble! I'm away atm, but when I get home in a few hours I can activate your account manually.

**Comment by skwerlman** [comment]
Hi, sorry for the delay. The first account, spicytomato, should be active now.
