### ISSUE TITLE
[Activation]: No Activation Email Received

### ISSUE THREAD

**Issue by Xainfried** [skwerlman/skwerlman.github.io#28]
### Account Name

Xainfried

### Reason

Never recieved email

### Server

- [X] This issue occurs on the Tetrarch Cockatrice server (mtg.tetrarch.co)

**Comment by skwerlman** [comment]
you should be activated now. Let me know if you have any issues

**Comment by TRsn1per** [comment]
I am having the same issues
ACCOUNT NAME: TRsn1per
Reason: Never received email.
Other info: No response

**Comment by skwerlman** [comment]
> I am having the same issues ACCOUNT NAME: TRsn1per Reason: Never received email. Other info: No response

Hi, I've activated your account.

In the future, please use the `New Issue` button rather than replying to closed or off-topic issues. When you reply to old/off-topic issues, it notifies _everyone_ involved in that topic, including people who are unable to help with your issue.
