### ISSUE TITLE
Problems registering a new account

### ISSUE THREAD

**Issue by jimmy2011** [skwerlman/skwerlman.github.io#3]
Today I tried to create a new account on the server "mtg.tetrach.co" and I could not. After following the correct steps, I was notified that a verification code would be sent to my email. But, no code has arrived. I've been waiting for almost an hour and nothing has come. I wonder if this is only happening to me or if someone else has this problem.

**Comment by skwerlman** [comment]
Hi, sorry for the late reply. Post your account name and I'll activate your account manually.

**Comment by jimmy2011** [comment]
My acc name is "jimmy2012".

**Comment by Tolamaker** [comment]
I currently have the exact same issue. Tolamaker is the account name.

**Comment by skwerlman** [comment]
activated
