### ISSUE TITLE
[Activation]: 

### ISSUE THREAD

**Issue by Bobeezzz** [skwerlman/skwerlman.github.io#31]
### Account Name

********

### Reason

Never recieved email

### Other Info

Hello,

Would appreciate your help.
Thank you.

### Server

- [X] This issue occurs on the Tetrarch Cockatrice server (mtg.tetrarch.co)

**Comment by skwerlman** [comment]
Your account should be activated now

**Comment by Bobeezzz** [comment]
Many thanks!
