### ISSUE TITLE
Server seems to be down.

### ISSUE THREAD

**Issue by LupusCenturion** [skwerlman/skwerlman.github.io#4]
Can't connect to the cockatrice server. every time I try it says "socket error".

**Comment by skwerlman** [comment]
Yep, sorry. I'm moving to a new house atm, and the server got moved out of the old one today. It should be back by the end of the weekend, and you can get live status info at https://status.tetrarch.co

**Comment by skwerlman** [comment]
@LupusCenturion Apologies for the extended downtime; there were some problems with the wiring at the new location. The server should be accessible again.
