### ISSUE TITLE
Tetrarch account activation key e-mails not being sent

### ISSUE THREAD

**Issue by Veryslightlymad** [skwerlman/skwerlman.github.io#6]
Hello. I am attempting to register an account on the tetrach server with Cockatrice, and it does not deliver an error message, but it does prompt me to add in my registration key. However, no e-mail was sent to my account. I know that it is the correct account because I have attempted to re-register, and it told me that I now already have an account with that e-mail address. I have no option to re-send the E-mail. The E-mail is not contained in any spam or other filter. I have attempted to make an account with two different E-mail addresses from the same E-mail client and from a second client, and neither of those received an activation key. I had a friend in another location attempt to register an account, and they ran into the same issue.

I apologize for making extra zombie accounts; I felt like it was necessary to troubleshoot the issue.

Let me know if any additional information is required to assist you, but as there is no actual error being displayed, I'm not sure what I would screenshot that would be of any value.

**Comment by skwerlman** [comment]
Hi, apologies for the inconvenience. This unfortunately appears to be caused by an issue with my email provider.

If you could provide me with the name of the account you tried to register, I can activate it manually for you.

**Comment by Veryslightlymad** [comment]
Sorry about the late reply. My account was Veryslightlymad, same as this one.

**Comment by skwerlman** [comment]
Sorry about the very extremely late reply; i was in europe for 2 weeks and not receiving any notifications.

Your account should be active now. Sorry again about the inconvenience.
