### ISSUE TITLE
Verification email not received

### ISSUE THREAD

**Issue by Patateha** [skwerlman/skwerlman.github.io#9]
Hi skwerlman,

I have not received the account activation email to the Cockatrice Tetrarch server. Could you please activate my account? The username is Patateha.

Thanks in advance!

**Comment by skwerlman** [comment]
Hi, sorry for the inconvenience. I see you tried to create 2 accounts; do you have a preference for which one you'd like activated?

**Comment by Patateha** [comment]
Hi, no worries. I’d prefer the one connected to email address
***@***.*** Many thanks

skwerlman ***@***.***> schrieb am So. 16. Okt. 2022 um 15:24:

**Comment by skwerlman** [comment]
Hi, apologies but it seems github is blocking you from sending the email in plain; can you just send me the username instead? The accounts are `Patateha` and `Patateha1`.

**Comment by Patateha** [comment]
Hi, Patateha without the 1 then.

skwerlman ***@***.***> schrieb am So. 16. Okt. 2022 um 18:00:

**Comment by skwerlman** [comment]
Should be activated now. Sorry again about the inconvenience.

**Comment by Patateha** [comment]
Yes, it works. Thank you very much

skwerlman ***@***.***> schrieb am So. 16. Okt. 2022 um 19:31:
